[tool.poetry]
name = "recovery"
version = "0.1.0"
description = ""
authors = ["Marcelo Villa-Piñeros <mvilla@humboldt.org.co>"]

[tool.poetry.dependencies]
python = "^3.8"
click = "^7.1.2"
Fiona = "^1.8.18"
geopandas = "^0.8.1"
numpy = "^1.19.4"
pandas = "^1.1.4"
rasterio = "^1.1.8"
rasterstats = "^0.15.0"
scipy = "^1.5.4"

[tool.poetry.dev-dependencies]
pytest = "^6.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
