[tool.poetry]
name = "recovery"
version = "0.1.0"
description = "Geographic and taxonomic verification of biological records."
license = "MIT"
authors = ["Marcelo Villa-Piñeros <mvilla@humboldt.org.co>"]
repository = "https://github.com/PEM-Humboldt/recovery"

[tool.poetry.dependencies]
python = "^3.8"
appdirs = "^1.4.4"
click = "^7.1.2"
Fiona = "^1.8.18"
gdown = "^3.12.2"
geopandas = "^0.8.1"
numpy = "^1.19.4"
pandas = "^1.1.4"
pygeos = "^0.8"
rasterio = "^1.1.8"
rasterstats = "^0.15.0"
scipy = "^1.5.4"
shapely = "^1.7.1"
requests = "^2.25.0"

[tool.poetry.dev-dependencies]
pytest = "^6.1.2"

[tool.poetry.scripts]
recovery = "recovery.cli.cli:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning:rasterstats",
    "ignore::RuntimeWarning:geopandas",
    "ignore::UserWarning:geopandas"
]
